#!/usr/bin/env bash
#
# Regenerate the static tool manifest from Dataclaw's GET /tools endpoint.
# Run this whenever you add, remove, or change tools in Dataclaw plugins.
#
# Usage:
#   ./sync-manifest.sh                          # default: http://localhost:8000
#   ./sync-manifest.sh http://localhost:9000     # custom URL
#

set -euo pipefail

DATACLAW_URL="${1:-http://localhost:8000}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
MANIFEST="$SCRIPT_DIR/src/tool-manifest.ts"

echo "Fetching tools from $DATACLAW_URL/api/tools ..."

TOOLS=$(curl -sf "$DATACLAW_URL/api/tools") || {
  echo "ERROR: Could not reach $DATACLAW_URL/api/tools"
  echo "Make sure Dataclaw is running: uv run python -m dataclaw"
  exit 1
}

python3 -c "
import sys, json

tools = json.loads('''$TOOLS''')
lines = [
    'import type { DataclawToolDefinition } from \"./types.js\";',
    '',
    '// Auto-generated by sync-manifest.sh — do not edit manually.',
    '// Regenerate: ./sync-manifest.sh',
    '',
    'export const DATACLAW_TOOL_MANIFEST: DataclawToolDefinition[] = [',
]
for t in tools:
    name = t['name']
    desc = t.get('description', '').replace('\\\\', '\\\\\\\\').replace('\"', '\\\\\"').replace('\\n', '\\\\n')
    params = json.dumps(t.get('parameters', {'type': 'object', 'properties': {}}))
    lines.append(f'  {{ name: \"{name}\", description: \"{desc}\", parameters: {params} }},')
lines.append('];')
print('\n'.join(lines))
" > "$MANIFEST"

COUNT=$(python3 -c "import json; print(len(json.loads('''$TOOLS''')))")
echo "Wrote $COUNT tools to $MANIFEST"
